name: Sprawdzenie projektu

on:
  push:
    branches: [main]

jobs:
  sprawdz:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Zainstaluj biblioteki
        run: pip install -r requirements.txt

      - name: Uruchom main.py
        run: python src/main.py
        